-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "subtotal" DECIMAL(65,30) NOT NULL DEFAULT 0.0,
ADD COLUMN     "taxAmount" DECIMAL(65,30) NOT NULL DEFAULT 0.0,
ADD COLUMN     "taxRate" DECIMAL(65,30) NOT NULL DEFAULT 0.0;
